display_name: Для своих
url: https://github.com/hiddify/hiddify-next/
license: Other

packager: hiddify
packagerEmail: linux@hiddify.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/USSR.png

keywords:
  - Для своих
  - Proxy
  - VPN
  - V2ray
  - Nekoray
  - Xray
  - Psiphon
  - OpenVPN

generic_name: Для своих

group: Applications/Internet

startup_notify: true
