display_name: Для своих
package_name: for-our-own
maintainer:
  name: hiddify
  email: linux@hiddify.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/USSR.png

postinstall_scripts:
  - echo "Installed Для своих"
postuninstall_scripts:
  - echo "Surprised Why?"

keywords:
  - Для своих
  - Proxy
  - VPN
  - V2ray
  - Nekoray
  - Xray
  - Psiphon
  - OpenVPN

generic_name: Для своих

categories:
  - Network

startup_notify: true
